### ISSUE TITLE
Stop Notify on the ECG Voltage Characteristic sometimes fails

### ISSUE THREAD

**Issue by stuartlynne** [JonasPrimbs/movesense-ble-ecg-firmware#2]
**Describe the bug**
I am using Python Bleak to get ECG data from the ECG Voltage Characteristic.

After successfully doing a start_notify and getting data, to stop the connection I use a stop_notify and then close the BLE client connection.

This apparently does not correctly get the Movesense to always correctly drop the connection.

The Movesense sensor (even after removing from the HR strap) continues to blink the red LED every 5 seconds. 

It does this until the battery is removed.

**To Reproduce**
I can provide a Python script to demonstrate if needed.

**Expected behaviour**
For the Movesense sensor to close the BLE connection, start advertising, and accept a new connection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Library: Bleak

**Comment by stuartlynne** [comment]
Seeing the same issue with the Movement service.

**Comment by JonasPrimbs** [comment]
Really sorry for the late response. I updated the firmware two days ago. Is the issue still there?

**Comment by JonasPrimbs** [comment]
Unable to reconstruct the issue on my side. Probably fixed in new firmware version.
Closing this issue as solved. Feel free to reopen if you still experience any issues.
