### ISSUE TITLE
Firmware v2.2

### ISSUE THREAD

**Issue by vlg-mxai** [JonasPrimbs/movesense-ble-ecg-firmware#3]
Do you plan to update for firmware v2.2?
[https://www.movesense.com/news/2023/12/movesense-sensor-firmware-2-2-published-new-features-and-improvements/]

**Comment by JonasPrimbs** [comment]
Yes, the update is planned.

Are you interested in specific features, e.g., two simultaneous Bluetooth connections?

I cannot promise, but it might take about 2 weeks. Please remind me in this thread if it takes longer.

**Comment by vlg-mxai** [comment]
Thank you for the quick reply!  My main interest is staying up to date and getting the bug fixes, but having simultaneous connections is enticing.

**Comment by JonasPrimbs** [comment]
I just released version 0.6.0 which uses firmware version 2.2.1.
I haven't adopted any other code yet, so probably connecting with multiple devices might not work.
Feel free to test the new firmware and provide feedback here!

**Comment by JonasPrimbs** [comment]
Closing this issue due to no complains about the new firmware.
