### ISSUE TITLE
Licensing of ble-ecg

### ISSUE THREAD

**Issue by MarelliF** [JonasPrimbs/movesense-ble-ecg-firmware#6]
**Is your feature request related to a problem? Please describe.**
I would like to use your code for academic research. However, no clear license is provided for your own contributions. The only licensing information available is the Movesense license, which should not cover your own code under ble-ecg.

**Describe the solution you'd like**
It would be nice if ble-ecg could have a clear license, for example a common open-source one like MIT or BSD-3, to clarify what uses of your code are legally permitted.

**Comment by JonasPrimbs** [comment]
I'm not a lawyer, so I'm not sure whether I can simply "override" the Movesense license. But from my side it is totally fine if you use my code from this repository.
However, if something with the code is wrong, don't sue me. I am not liable for it.
I would also appreciate it if you cite the paper linked in the README document in your scientific publication.
